"use client";
import { createContext, useContext, useState, useCallback, useEffect } from "react";
const translations = {
  en: { dashboard: "Dashboard", products: "Products", orders: "Orders", users: "Users", reports: "Reports", sponsorships: "Sponsorships", login: "Login", logout: "Logout", email: "Email", password: "Password", search: "Search", save: "Save", cancel: "Cancel", delete: "Delete", edit: "Edit", add: "Add", approve: "Approve", reject: "Reject", pending: "Pending", approved: "Approved", rejected: "Rejected", total: "Total", status: "Status", actions: "Actions", name: "Name", price: "Price", stock: "Stock", category: "Category", supplier: "Supplier", customer: "Customer", date: "Date", all: "All", loading: "Loading...", no_data: "No data found", confirm: "Confirm", settings: "Settings", profile: "Profile", overview: "Overview", revenue: "Revenue", profit: "Profit", wholesale: "Wholesale Cost", retail: "Retail Price", suggested: "Suggested Price", my_products: "My Products", my_orders: "My Orders", add_product: "Add Product", view: "View", details: "Details", order_number: "Order #", quantity: "Qty", amount: "Amount", phone: "Phone", address: "Address", active: "Active", inactive: "Inactive", delivered: "Delivered", shipped: "Shipped", confirmed: "Confirmed", cancelled: "Cancelled", paid: "Paid", unpaid: "Unpaid", categories: "Categories", content: "Content", messages: "Messages", delivery: "Delivery", admin: "Admin", export_csv: "Export CSV", assign: "Assign", change_role: "Change Role", deactivate: "Deactivate", activate: "Activate", company: "Company", province: "Province", district: "District", village: "Village", weight: "Weight", dimensions: "Dimensions", material: "Material", margin: "Margin", quick_actions: "Quick Actions" },
  ps: { dashboard: "ډشبورډ", products: "محصولات", orders: "سپارښتنې", users: "کاروونکي", reports: "رپوټونه", sponsorships: "سپانسرشپ", login: "ننوتل", logout: "وتل", email: "ایمیل", password: "پاسورډ", search: "لټون", save: "خوندي کول", cancel: "لغوه", delete: "حذف", edit: "سمول", add: "اضافه", approve: "تصویب", reject: "رد", pending: "انتظار", approved: "تصویب شوی", rejected: "رد شوی", total: "ټول", status: "حالت", actions: "عملیات", name: "نوم", price: "قیمت", stock: "ذخیره", category: "کتګوري", supplier: "عرضه کوونکی", customer: "پیرودونکی", date: "نیټه", all: "ټول", loading: "لوډ کیږي...", no_data: "معلومات نشته", confirm: "تایید", settings: "تنظیمات", profile: "پروفایل", overview: "لنډیز", revenue: "عاید", profit: "ګټه", wholesale: "عمده قیمت", retail: "پرچون قیمت", suggested: "وړاندیز شوی قیمت", my_products: "زما محصولات", my_orders: "زما سپارښتنې", add_product: "محصول اضافه", view: "لیدل", details: "جزئیات", order_number: "د سپارښتنې #", quantity: "مقدار", amount: "اندازه", phone: "تلیفون", address: "پته", active: "فعال", inactive: "غیرفعال", delivered: "تحویل شوی", shipped: "لیږل شوی", confirmed: "تایید شوی", cancelled: "لغو شوی", paid: "تادیه شوی", unpaid: "تادیه نشوی", categories: "کتګوریونه", content: "منځپانګه", messages: "پیغامونه", delivery: "تحویل", admin: "اډمین", export_csv: "CSV صدور", assign: "ځای پرځای کول", change_role: "رول بدلول", deactivate: "غیرفعال کول", activate: "فعال کول", company: "شرکت", province: "ولایت", district: "ولسوالي", village: "کلی", weight: "وزن", dimensions: "اندازې", material: "مواد", margin: "حاشیه", quick_actions: "چټکې کړنې" },
  dr: { dashboard: "داشبورد", products: "محصولات", orders: "سفارشات", users: "کاربران", reports: "گزارشات", sponsorships: "اسپانسرشیپ", login: "ورود", logout: "خروج", email: "ایمیل", password: "رمز عبور", search: "جستجو", save: "ذخیره", cancel: "لغو", delete: "حذف", edit: "ویرایش", add: "اضافه", approve: "تایید", reject: "رد", pending: "در انتظار", approved: "تایید شده", rejected: "رد شده", total: "مجموع", status: "وضعیت", actions: "عملیات", name: "نام", price: "قیمت", stock: "موجودی", category: "دسته", supplier: "تامین کننده", customer: "مشتری", date: "تاریخ", all: "همه", loading: "بارگذاری...", no_data: "داده‌ای یافت نشد", confirm: "تایید", settings: "تنظیمات", profile: "پروفایل", overview: "نمای کلی", revenue: "درآمد", profit: "سود", wholesale: "قیمت عمده", retail: "قیمت خرده", suggested: "قیمت پیشنهادی", my_products: "محصولات من", my_orders: "سفارشات من", add_product: "افزودن محصول", view: "مشاهده", details: "جزئیات", order_number: "شماره سفارش", quantity: "تعداد", amount: "مقدار", phone: "تلفن", address: "آدرس", active: "فعال", inactive: "غیرفعال", delivered: "تحویل داده شده", shipped: "ارسال شده", confirmed: "تایید شده", cancelled: "لغو شده", paid: "پرداخت شده", unpaid: "پرداخت نشده", categories: "دسته‌بندی‌ها", content: "محتوا", messages: "پیام‌ها", delivery: "تحویل", admin: "مدیر", export_csv: "خروجی CSV", assign: "تخصیص", change_role: "تغییر نقش", deactivate: "غیرفعال کردن", activate: "فعال کردن", company: "شرکت", province: "ولایت", district: "ولسوالی", village: "قریه", weight: "وزن", dimensions: "ابعاد", material: "جنس", margin: "حاشیه", quick_actions: "اقدامات سریع" },
};
const Ctx = createContext({});
export const useLanguage = () => useContext(Ctx);
export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState("en");
  useEffect(() => { const s = localStorage.getItem("sawdagar_admin_lang"); if (s) setLangState(s); }, []);
  const setLang = useCallback((l) => { setLangState(l); localStorage.setItem("sawdagar_admin_lang", l); }, []);
  const t = useCallback((key) => translations[lang]?.[key] || translations.en[key] || key, [lang]);
  const isRTL = lang === "ps" || lang === "dr";
  return <Ctx.Provider value={{ lang, setLang, t, isRTL }}>{children}</Ctx.Provider>;
}
